Repository mendableai/firecrawl, pull requests merged in 2024-05, with the labels that each got.

#126 [Feat] Added includeHTML option
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/crawl.ts
  apps/api/src/controllers/crawlPreview.ts
  apps/api/src/controllers/scrape.ts
  apps/api/src/controllers/search.ts
  apps/api/src/lib/entities.ts
  apps/api/src/main/runWebScraper.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/types.ts
Labels: ready to merge

#129 Cancel Job Route
  apps/api/fly.toml
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/crawl-cancel.ts
  apps/api/src/controllers/crawl.ts
  apps/api/src/lib/entities.ts
  apps/api/src/main/runWebScraper.ts
  apps/api/src/routes/v0.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/services/logging/crawl_log.ts
Labels: ready to merge

#130 [Feat] Added max depth option
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/index.ts
Labels: ready to merge

#135 Adds Zod Integration for LLM Extraction in the Firecrawl JS SDK
  README.md
  apps/js-sdk/firecrawl/build/index.js
  apps/js-sdk/firecrawl/package-lock.json
  apps/js-sdk/firecrawl/package.json
  apps/js-sdk/firecrawl/src/index.ts
  apps/js-sdk/firecrawl/types/index.d.ts
  apps/js-sdk/package-lock.json
  apps/js-sdk/package.json
  apps/js-sdk/test.ts
  apps/js-sdk/tsconfig.json
  apps/python-sdk/README.md
  apps/python-sdk/build/lib/firecrawl/firecrawl.py
  apps/python-sdk/dist/firecrawl-py-0.0.6.tar.gz
  apps/python-sdk/dist/firecrawl-py-0.0.8.tar.gz
  apps/python-sdk/dist/firecrawl_py-0.0.6-py3-none-any.whl
  apps/python-sdk/dist/firecrawl_py-0.0.8-py3-none-any.whl
  apps/python-sdk/example.py
  apps/python-sdk/firecrawl/firecrawl.py
  apps/python-sdk/firecrawl_py.egg-info/PKG-INFO
  apps/python-sdk/setup.py
Labels: ready to merge, high-priority

#134 Switching to AGPL - We Need Your Consent!
  LICENSE
Labels: ready to merge, high-priority

#142 [Doc] Added default value for crawlOptions.limit
  apps/api/openapi.json
Labels: ready to merge

#119 Add Docker Compose for easy self hosting
  SELF_HOST.md
  apps/api/.env.example
  docker-compose.yaml
Labels: documentation, ready to merge, self-host, waiting-for-license

#27 refactor: fix typo in WebScraper/index.ts
  apps/api/src/scraper/WebScraper/index.ts
Labels: in review, waiting-for-license

#153 [Tests] Added crawl test suite -> crawl improvements
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/services/rate-limiter.ts
  apps/python-sdk/firecrawl/firecrawl.py
  apps/test-suite/data/crawl.json
  apps/test-suite/data/scrape.json
  apps/test-suite/package.json
  apps/test-suite/tests/crawl.test.ts
  apps/test-suite/tests/scrape.test.ts
  apps/test-suite/tsconfig.json
Labels: ready to merge

#158 feat: Docx Support
  apps/api/package.json
  apps/api/pnpm-lock.yaml
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/utils/__tests__/docxProcessor.test.ts
  apps/api/src/scraper/WebScraper/utils/docxProcessor.ts
Labels: ready to merge

#29 Fixes pdfs not found if .pdf is not present
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/utils/pdfProcessor.ts
Labels: ready to merge

#151 [Feat] Added rate limits
  apps/api/.env.example
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/auth.ts
  apps/api/src/services/rate-limiter.ts
Labels: ready to merge

#77 Add additional file extensions to crawler.ts
  apps/api/src/scraper/WebScraper/crawler.ts
Labels: ready to merge

#143 [Bug] Fixing /crawl limit
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/scraper/WebScraper/crawler.ts
Labels: bug, ready to merge

#181 [Feat] Added proxy and media blocking support for Playwright
  apps/api/.env.example
  apps/playwright-service/main.py
  docker-compose.yaml
Labels: enhancement

#168 feat: Allow privacy/legal/ other pages in social media websites
  apps/api/src/scraper/WebScraper/utils/blocklist.ts
Labels: ready to merge

#176 [Bug] Added data check for python SDK
  apps/python-sdk/firecrawl/firecrawl.py
Labels: bug, ready to merge

#132 [Feat] Added idempotency key to crawl route
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/crawl.ts
  apps/api/src/services/idempotency/create.ts
  apps/api/src/services/idempotency/validate.ts
  apps/js-sdk/example.js
  apps/js-sdk/firecrawl/build/index.js
  apps/js-sdk/firecrawl/package.json
  apps/js-sdk/firecrawl/src/index.ts
  apps/js-sdk/firecrawl/types/index.d.ts
  apps/js-sdk/package-lock.json
  apps/js-sdk/package.json
  apps/python-sdk/example.py
  apps/python-sdk/firecrawl/firecrawl.py
Labels: ready to merge, in review

#190 Feat: Provide more details for 429 error msg
  apps/api/src/controllers/auth.ts
Labels: ready to merge, in review

#186 Limit on /search is not deterministic
  apps/api/src/controllers/search.ts
Labels: ready to merge

#191 Various PyPi Metadata
  apps/python-sdk/dist/firecrawl-py-0.0.10.tar.gz
  apps/python-sdk/dist/firecrawl-py-0.0.11.tar.gz
  apps/python-sdk/dist/firecrawl_py-0.0.10-py3-none-any.whl
  apps/python-sdk/dist/firecrawl_py-0.0.11-py3-none-any.whl
  apps/python-sdk/firecrawl_py.egg-info/PKG-INFO
  apps/python-sdk/setup.py
Labels: in review

#200 Allow users to manually set the waitFor param on /scrape
  apps/api/openapi.json
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/scrape.ts
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: in review

#204 [Feat] Added custom scraping conditions for readme docs
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: ready to merge
