Repository mendableai/firecrawl, pull requests merged in 2024-07, with the labels that each got.

#336 [Proposal] new feature allowExternalContentLinks
  apps/api/src/__tests__/e2e_full_withAuth/index.test.ts
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/index.ts
Labels: ready to merge

#338 [PROPOSAL] (deps): making sure all deps are always up to date
  .github/dependabot.yml
Labels: ready to merge

#337 [PROPOSAL] (docker-compose) regroup envs vars between services
  docker-compose.yaml
Labels: ready to merge

#325 new playwright service
  .gitignore
  apps/playwright-service-ts/README.md
  apps/playwright-service-ts/api.ts
  apps/playwright-service-ts/helpers/get_error.ts
  apps/playwright-service-ts/package.json
  apps/playwright-service-ts/tsconfig.json
Labels: ready to merge

#363 Logging for all scraper methods
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/global.ts
  apps/api/src/scraper/WebScraper/scrapers/fetch.ts
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
  apps/api/src/scraper/WebScraper/scrapers/playwright.ts
  apps/api/src/scraper/WebScraper/scrapers/scrapingBee.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/services/logging/scrape_log.ts
  apps/api/src/types.ts
Labels: ready to merge

#361 setting up docker to ts playwright service
  apps/playwright-service-ts/Dockerfile
  apps/playwright-service-ts/tsconfig.json
Labels: ready to merge, self-host

#362 (Docs) Self Host added new ts playwright service instructions
  SELF_HOST.md
Labels: documentation, ready to merge, in review, self-host

#374 Only check Supabase if configured to when cancelling job
  apps/api/src/controllers/crawl-cancel.ts
Labels: ready to merge, self-host

#370 dependabot for security checks, fixed crawl test
  .github/dependabot.yml
  apps/test-suite/data/crawl.json
  apps/test-suite/tests/crawl.test.ts
Labels: ready to merge

#326 [Feat] Added implementation for saving docs on supabase
  .github/workflows/fly-direct.yml
  .github/workflows/fly.yml
  apps/api/Dockerfile
  apps/api/fly.staging.toml
  apps/api/fly.toml
  apps/api/package.json
  apps/api/postdeploy.js
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/crawl-status.ts
  apps/api/src/controllers/status.ts
  apps/api/src/index.ts
  apps/api/src/lib/supabase-jobs.ts
  apps/api/src/main/runWebScraper.ts
  apps/api/src/services/logging/log_job.ts
  apps/api/src/services/queue-worker.ts
  apps/api/src/trigger-shutdown.ts
  apps/api/src/types.ts
Labels: ready to merge

#375 Self-hosting quality of life fixes
  apps/api/src/services/webhook.ts
  docker-compose.yaml
Labels: ready to merge, self-host

#386 [Feat] Added fire-engine fallback for getting sitemaps
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/sitemap.ts
Labels: in review

#395 Fix USE_DB_AUTHENTICATION checks for self-host
  apps/api/src/controllers/crawl-status.ts
  apps/api/src/controllers/status.ts
  apps/api/src/main/runWebScraper.ts
  apps/api/src/services/logging/log_job.ts
Labels: ready to merge, self-host

#396 [BUG] Fixed docker self hosting issue
  apps/api/src/services/logging/crawl_log.ts
  docker-compose.yaml
Labels: ready to merge

#397 Slack Alerts for when queue is over capacity
  apps/api/src/index.ts
  apps/api/src/main/runWebScraper.ts
  apps/api/src/services/alerts/index.ts
  apps/api/src/services/alerts/slack.ts
Labels: ready to merge

#394 Log Fire-engine page errors
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
Labels: ready to merge

#399 Sitemap fallback fixes w/ fire-engine
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
  apps/api/src/scraper/WebScraper/sitemap.ts
  apps/api/src/scraper/WebScraper/utils/custom/website_params.ts
Labels: ready to merge

#417 Separate Rate Limiter from Main Redis
  apps/api/src/services/rate-limiter.ts
Labels: ready to merge

#391 [Feat] Pass along current, total, current_step, and current_url in js sdk
  apps/js-sdk/firecrawl/build/index.js
  apps/js-sdk/firecrawl/package-lock.json
  apps/js-sdk/firecrawl/package.json
  apps/js-sdk/firecrawl/src/__tests__/e2e_withAuth/index.test.ts
  apps/js-sdk/firecrawl/src/index.ts
Labels: bug, in review, js-sdk

#424 Redis Health Checks
  .github/workflows/check-redis.yml
  apps/api/package.json
  apps/api/pnpm-lock.yaml
  apps/api/src/index.ts
  apps/api/src/services/rate-limiter.test.ts
  apps/api/src/services/rate-limiter.ts
  apps/api/src/services/redis.ts
Labels: ready to merge

#423 Caleb: Return a list of links on a page by default
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/__tests__/single_url.test.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/utils/utils.ts
Labels: enhancement, in review

#429 Fix queue stuck bug via lock settings changes
  apps/api/fly.staging.toml
  apps/api/fly.toml
  apps/api/package.json
  apps/api/postdeploy.js
  apps/api/src/index.ts
  apps/api/src/services/queue-service.ts
  apps/api/src/services/queue-worker.ts
  apps/api/src/trigger-shutdown.ts
Labels: ready to merge

#436 fix(WebScraper): infinite regex leading to fly.io instance hangs
  apps/api/src/scraper/WebScraper/utils/replacePaths.ts
Labels: ready to merge

#410 Support chrome-cdp and restructure sitemap fire-engine support.
  apps/api/src/controllers/crawl-cancel.ts
  apps/api/src/controllers/status.ts
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/sitemap.ts
  apps/api/src/scraper/WebScraper/utils/custom/website_params.ts
  apps/api/src/services/queue-service.ts
Labels: ready to merge

#447 /scrape should now be 600ms-900ms faster
  apps/api/src/controllers/scrape.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/sitemap.ts
  apps/api/src/services/billing/credit_billing.ts
Labels: ready to merge

#453 Notion Website Fixes
  apps/api/src/scraper/WebScraper/utils/custom/website_params.ts
Labels: ready to merge

#450 Added logger
  apps/api/.env.example
  apps/api/src/__tests__/e2e_full_withAuth/index.test.ts
  apps/api/src/controllers/auth.ts
  apps/api/src/controllers/crawl-cancel.ts
  apps/api/src/controllers/crawl-status.ts
  apps/api/src/controllers/crawl.ts
  apps/api/src/controllers/crawlPreview.ts
  apps/api/src/controllers/scrape.ts
  apps/api/src/controllers/search.ts
  apps/api/src/controllers/status.ts
  apps/api/src/index.ts
  apps/api/src/lib/LLM-extraction/index.ts
  apps/api/src/lib/logger.ts
  apps/api/src/lib/withAuth.ts
  apps/api/src/main/runWebScraper.ts
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/custom/handleCustomScraping.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/scrapers/fetch.ts
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
  apps/api/src/scraper/WebScraper/scrapers/playwright.ts
  apps/api/src/scraper/WebScraper/scrapers/scrapingBee.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/sitemap.ts
  apps/api/src/scraper/WebScraper/utils/__tests__/socialBlockList.test.ts
  apps/api/src/scraper/WebScraper/utils/blocklist.ts
  apps/api/src/scraper/WebScraper/utils/imageDescription.ts
  apps/api/src/scraper/WebScraper/utils/metadata.ts
  apps/api/src/scraper/WebScraper/utils/pdfProcessor.ts
  apps/api/src/scraper/WebScraper/utils/replacePaths.ts
  apps/api/src/scraper/WebScraper/utils/utils.ts
  apps/api/src/search/googlesearch.ts
  apps/api/src/search/index.ts
  apps/api/src/services/alerts/index.ts
  apps/api/src/services/alerts/slack.ts
  apps/api/src/services/billing/credit_billing.ts
  apps/api/src/services/idempotency/create.ts
  apps/api/src/services/idempotency/validate.ts
  apps/api/src/services/logging/crawl_log.ts
  apps/api/src/services/logging/log_job.ts
  apps/api/src/services/logging/scrape_log.ts
  apps/api/src/services/logtail.ts
  apps/api/src/services/notification/email_notification.ts
  apps/api/src/services/posthog.ts
  apps/api/src/services/queue-service.ts
  apps/api/src/services/queue-worker.ts
  apps/api/src/services/redis.ts
  apps/api/src/services/supabase.ts
  apps/api/src/services/webhook.ts
  apps/test-suite/utils/supabase.ts
Labels: ready to merge

#457 Readiness liveness probes
  apps/api/src/controllers/liveness.ts
  apps/api/src/controllers/readiness.ts
  apps/api/src/routes/v0.ts
  apps/playwright-service/main.py
  examples/kubernetes/cluster-install/README.md
  examples/kubernetes/cluster-install/api.yaml
  examples/kubernetes/cluster-install/configmap.yaml
  examples/kubernetes/cluster-install/playwright-service.yaml
  examples/kubernetes/cluster-install/worker.yaml
Labels: ready to merge

#460 Admin router + Improve redis notifications
  apps/api/src/controllers/admin/queue.ts
  apps/api/src/controllers/admin/redis-health.ts
  apps/api/src/index.ts
  apps/api/src/routes/admin.ts
Labels: ready to merge

#414 support custom models
  apps/api/src/lib/LLM-extraction/models.ts
  docker-compose.yaml
Labels: ready to merge

#479 Fire-engine to be the default for our cloud-service
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: ready to merge

#483 [Feat] Better self hosting guide
  SELF_HOST.md
Labels: ready to merge

#484 Fix parallelization issues with caching
  apps/api/package.json
  apps/api/pnpm-lock.yaml
  apps/api/src/controllers/scrape.ts
  apps/api/src/lib/scrape-events.ts
  apps/api/src/scraper/WebScraper/__tests__/single_url.test.ts
  apps/api/src/services/billing/credit_billing.ts
Labels: ready to merge

#485 [Bug] Issue with crawl going beyond Limit
  apps/api/src/scraper/WebScraper/crawler.ts
Labels: ready to merge
