Repository mendableai/firecrawl, pull requests merged in 2024-06, with the labels that each got.

#228 Fixed fire-engine content bug
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: bug

#221 feat: Ability to forward headers to reliable providers for auth etc...
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/utils/custom/website_params.ts
  apps/playwright-service/main.py
Labels: ready to merge

#185 Improvements to the blocklist regex
  apps/api/src/scraper/WebScraper/utils/__tests__/socialBlockList.test.ts
  apps/api/src/scraper/WebScraper/utils/blocklist.ts
Labels: ready to merge

#211 [Fix] Changed timeout parameter name on js sdk
  apps/js-sdk/firecrawl/src/index.ts
Labels: ready to merge

#235 [Feat] Added custom scraping for google-drive pdf usecase
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: enhancement, ready to merge

#213 Script to check local vs published versions of sdk packages
  .github/scripts/check_version_has_incremented.py
  .github/scripts/requirements.txt
Labels: in review, ci

#234 Add support for Self-Hosted Webhook URL Usage and added project_id into the webhook payload
  apps/api/.env.example
  apps/api/src/services/webhook.ts
Labels: enhancement, question, ready to merge

#196 Python-SDK transitional build setup for pyproject.toml
  apps/python-sdk/firecrawl/__init__.py
  apps/python-sdk/pyproject.toml
  apps/python-sdk/setup.py
Labels: in review

#262 Only fetch webhook from db if self host webhook not set and using db auth
  apps/api/src/services/webhook.ts
Labels: ready to merge

#272 [Feat] Added jobId to webhook data
  apps/api/src/services/queue-worker.ts
  apps/api/src/services/webhook.ts
Labels: enhancement

#256 Added logging to python sdk FIRECRAWL_LOGGING_LEVEL
  apps/python-sdk/firecrawl/__init__.py
  apps/python-sdk/firecrawl/__tests__/e2e_withAuth/__pycache__/test.cpython-311-pytest-8.2.1.pyc
  apps/python-sdk/firecrawl/firecrawl.py
Labels: ready to merge

#253 Python sdk improve response handling
  apps/python-sdk/firecrawl/__init__.py
  apps/python-sdk/firecrawl/__tests__/e2e_withAuth/test.py
  apps/python-sdk/firecrawl/firecrawl.py
Labels: ready to merge

#271 [Feat] Added parsePDF option to pageOptions
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/crawl.ts
  apps/api/src/controllers/scrape.ts
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/custom/handleCustomScraping.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/utils/__tests__/pdfProcessor.test.ts
  apps/api/src/scraper/WebScraper/utils/pdfProcessor.ts
Labels: enhancement

#296 Added local host support for the javascript SDK
  apps/js-sdk/firecrawl/README.md
  apps/js-sdk/firecrawl/build/index.js
  apps/js-sdk/firecrawl/package-lock.json
  apps/js-sdk/firecrawl/package.json
  apps/js-sdk/firecrawl/src/index.ts
  apps/js-sdk/firecrawl/types/index.d.ts
  apps/js-sdk/package-lock.json
Labels: ready to merge

#297 [Feat] Added support for RegEx in removeTags
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/utils/__tests__/removeUnwantedElements.test.ts
  apps/api/src/scraper/WebScraper/utils/removeUnwantedElements.ts
Labels: enhancement, ready to merge

#301 [Bug] Fixed includeHTML to use cleanedHtml as response
  apps/api/package.json
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: ready to merge

#303 Fix Broken Link
  SELF_HOST.md
Labels: ready to merge

#316 add some types
  apps/api/src/main/runWebScraper.ts
  apps/api/src/types.ts
Labels: ready to merge

#322 [Test] Added E2E tests for checking metadata values
  apps/api/src/__tests__/e2e_full_withAuth/index.test.ts
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
Labels: ready to merge

#328 pageOptions.onlyIncludeTags param
  apps/api/openapi.json
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/utils/__tests__/removeUnwantedElements.test.ts
  apps/api/src/scraper/WebScraper/utils/removeUnwantedElements.ts
Labels: ready to merge

#329 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready to merge
