Repository mendableai/firecrawl, pull requests merged in 2024-08, with the labels that each got.

#475 [Bug] pdfs and logging pdf events, also added trycatchs for docx
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/utils/docxProcessor.ts
  apps/api/src/scraper/WebScraper/utils/pdfProcessor.ts
Labels: ready to merge

#503 [Bug] Fixed the empty excludes.filter is undefined bug
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/index.ts
Labels: ready to merge

#504 [Feat] Added fullpagescreenshot capabilities
  apps/api/openapi.json
  apps/api/src/lib/default-values.ts
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: ready to merge

#496 Improve logs
  apps/api/src/services/supabase.ts
  docker-compose.yaml
Labels: ready to merge, logging

#512 Digikey support
  apps/api/src/scraper/WebScraper/utils/custom/website_params.ts
Labels: ready to merge

#497 [Feat] Add Go SDK implementation
  .github/workflows/fly.yml
  apps/go-sdk/.env.example
  apps/go-sdk/LICENSE
  apps/go-sdk/README.md
  apps/go-sdk/examples/example.go
  apps/go-sdk/examples/go.mod
  apps/go-sdk/examples/go.sum
  apps/go-sdk/firecrawl/firecrawl.go
  apps/go-sdk/firecrawl/firecrawl_test.go
  apps/go-sdk/go.mod
  apps/go-sdk/go.sum
Labels: ready to merge

#529 Redlock cache in auth
  apps/api/src/controllers/auth.ts
  apps/api/src/index.ts
  apps/api/src/services/billing/credit_billing.ts
  apps/api/src/services/redlock.ts
  apps/js-sdk/firecrawl/build/cjs/index.js
  apps/js-sdk/firecrawl/package-lock.json
  apps/js-sdk/firecrawl/package.json
Labels: ready to merge

#515 Update redis urls in example .env
  SELF_HOST.md
  apps/api/.env.example
Labels: ready to merge

#531 Self-host fix: Moving comments of .env.example values from end-of-line to above-line.
  apps/api/.env.example
Labels: ready to merge

#536 Fixed e2e tests
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
Labels: ready to merge

#532 Removed obsoleted declaration
  docker-compose.yaml
Labels: ready to merge

#459 feat: Move scraper to queue
  apps/api/fly.staging.toml
  apps/api/fly.toml
  apps/api/package.json
  apps/api/pnpm-lock.yaml
  apps/api/src/__tests__/e2e_withAuth/index.test.ts
  apps/api/src/controllers/admin/queue.ts
  apps/api/src/controllers/crawl-cancel.ts
  apps/api/src/controllers/crawl-status.ts
  apps/api/src/controllers/crawl.ts
  apps/api/src/controllers/crawlPreview.ts
  apps/api/src/controllers/scrape.ts
  apps/api/src/controllers/search.ts
  apps/api/src/controllers/status.ts
  apps/api/src/index.ts
  apps/api/src/lib/crawl-redis.ts
  apps/api/src/lib/entities.ts
  apps/api/src/lib/scrape-events.ts
  apps/api/src/lib/validateUrl.ts
  apps/api/src/main/runWebScraper.ts
  apps/api/src/run-req.ts
  apps/api/src/scraper/WebScraper/__tests__/single_url.test.ts
  apps/api/src/scraper/WebScraper/crawler.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/scraper/WebScraper/utils/utils.ts
  apps/api/src/services/alerts/index.ts
  apps/api/src/services/logging/log_job.ts
  apps/api/src/services/queue-jobs.ts
  apps/api/src/services/queue-service.ts
  apps/api/src/services/queue-worker.ts
  apps/api/src/services/system-monitor.ts
  apps/api/src/types.ts
  apps/test-suite/package.json
  apps/test-suite/pnpm-lock.yaml
Labels: ready to merge

#480 Reduce metrics ingestion w/ HyperDX v0.8.1
  apps/api/package.json
  apps/api/pnpm-lock.yaml
Labels: ready to merge

#555 added variables to beta customers
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
  apps/api/src/scraper/WebScraper/single_url.ts
Labels: ready to merge

#561 [Bug] Added a way for dealing with DNS without IP resolution
  apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
Labels: ready to merge

#566 Internal Concurrency Limits <> Job Priorities
  apps/api/src/controllers/auth.ts
  apps/api/src/controllers/crawl.ts
  apps/api/src/controllers/crawlPreview.ts
  apps/api/src/controllers/scrape.ts
  apps/api/src/controllers/search.ts
  apps/api/src/index.ts
  apps/api/src/lib/__tests__/job-priority.test.ts
  apps/api/src/lib/crawl-redis.ts
  apps/api/src/lib/job-priority.ts
  apps/api/src/services/queue-jobs.ts
  apps/api/src/services/queue-worker.ts
  apps/api/src/types.ts
Labels: ready to merge

#373 [Feat]: Add RUST SDK client for firecrawl API
  .github/archive/publish-rust-sdk.yml
  .github/archive/rust-sdk.yml
  .github/scripts/check_version_has_incremented.py
  .github/scripts/requirements.txt
  .github/workflows/fly.yml
  apps/rust-sdk/.gitignore
  apps/rust-sdk/CHANGELOG.md
  apps/rust-sdk/Cargo.lock
  apps/rust-sdk/Cargo.toml
  apps/rust-sdk/README.md
  apps/rust-sdk/examples/example.rs
  apps/rust-sdk/src/lib.rs
  apps/rust-sdk/tests/.env.example
  apps/rust-sdk/tests/e2e_with_auth.rs
Labels: enhancement, ready to merge

#593 Fixed RPC cloudflare issues with job ids
  apps/api/src/lib/supabase-jobs.ts
Labels: ready to merge

#586 [v1] LLM Extract
  README.md
  apps/api/package.json
  apps/api/pnpm-lock.yaml
  apps/api/src/controllers/v0/scrape.ts
  apps/api/src/controllers/v1/scrape.ts
  apps/api/src/controllers/v1/types.ts
  apps/api/src/lib/LLM-extraction/index.ts
  apps/api/src/lib/LLM-extraction/models.ts
  apps/api/src/lib/custom-error.ts
  apps/api/src/lib/entities.ts
  apps/api/src/scraper/WebScraper/__tests__/single_url.test.ts
  apps/api/src/scraper/WebScraper/index.ts
  apps/api/src/scraper/WebScraper/single_url.ts
  apps/api/src/services/billing/credit_billing.ts
  apps/api/src/services/queue-jobs.ts
  apps/api/src/services/queue-worker.ts
  apps/js-sdk/firecrawl/build/cjs/index.js
  apps/js-sdk/firecrawl/build/esm/index.js
  apps/js-sdk/firecrawl/src/index.ts
  apps/js-sdk/firecrawl/types/index.d.ts
  apps/python-sdk/example.py
  apps/python-sdk/firecrawl/firecrawl.py
Labels: ready to merge
